---
After: framework
---
SilverStripe\Control\Director:
  rules:
    '': HomeController
    add-ons: AddonsController
    vendors: VendorsController
    authors: AuthorsController
    tags: TagsController
    submit: SubmitAddonController
    addonSort: AjaxController
    'api/supported-addons': SupportedAddonsApiController
