---
After: framework
---
SilverStripe\Control\Director:
  rules:
    '': HomeController
    add-ons: AddonsController
    author: AuthorController
    tags: TagsController
    submit: SubmitAddonController
    addonSort: AjaxController
    'api/supported-addons': SupportedAddonsApiController
